### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ylmeng** [hllorens/timeml-normalizer#1]
Sometimes I got errors like this:

Errors found (TimeML_Normalizer):
	java.lang.NullPointerException

The input file has correct timeml format, and also has TEXT, DCT tags and so on, but gets an error. The error message is not quite helpful here.

**Comment by hllorens** [comment]
Please try with -d (debug mode) and paste the output.

Thanks!

**Comment by ylmeng** [comment]
Hi, thanks for replying. I generated the output like this:
...
Normalizing (respect=true) annotation_1 original timex t436 last_tid=6 open_timex=[0, 0] 
Normalizing (respect=true) annotation_1 original timex t495 last_tid=7 open_timex=[0, 0] 
Normalizing (respect=true) annotation_0 original timex t1003 last_tid=8 open_timex=[0, 0] 
Normalizing (respect=true) annotation_1 original timex t534 last_tid=8 open_timex=[1003, 0] 
	Trying to pair 8 with respected t1003
		Paired
Normalizing (respect=true) annotation_1 original timex t555 last_tid=8 open_timex=[0, 0] 
Normalizing (respect=true) annotation_1 original timex t570 last_tid=9 open_timex=[0, 0] 
Normalizing (respect=true) annotation_1 original timex t620 last_tid=10 open_timex=[0, 0] 
Normalizing (respect=true) annotation_1 original timex t672 last_tid=11 open_timex=[0, 0] 
Errors found (TimeML_Normalizer):
	java.lang.NullPointerException

java.lang.NullPointerException
	at com.cognitionis.timeml_normalizer.TimeML_Normalizer.normalize(TimeML_Normalizer.java:358)
	at com.cognitionis.timeml_normalizer.Main.main(Main.java:112)

Our input file is here https://github.com/ylmeng/TEA/blob/master/data/james_brady_dies.ascii.TE3input.tml It has a lot of (too many) EVENT and TIMEX3 tags on purpose. 
The original file is james_brady_dies.ascii.TE3input.tml provided in http://alt.qcri.org/semeval2015/task5/index.php?id=data-and-tools We also uploaded it here https://github.com/ylmeng/TEA/blob/master/test-tools-and-data/qa-tempeval-test-news/eval-questions/question-events/james_brady_dies.ascii.TE3input.tml

I will also do a little big of debugging but I suppose you know better.

**Comment by hllorens** [comment]
since this is the line that failed:

```
at com.cognitionis.timeml_normalizer.TimeML_Normalizer.normalize(TimeML_Normalizer.java:358)
                            if (mks_new_ids.contains(mapped_event.replaceFirst("e", "ei"))) {
```

and mks_new_ids cannot be null I assume it is mapped_event.
Then
For that to be null this must have resulted in null
`String mapped_event = event_map[a].get(element.getAttribute("eventID"));`

For that to happen  `element.getAttribute("eventID")`  must have provided something that is not in the `event_map[a]`.

My suggestion is that you create a MR (merge request/pull request) that adds a validation like

`if(mapped_event==null) { show information about which event failed and all the needed information}`

My guess is that the TimeML of your file is not valid. Have you validated it with https://github.com/hllorens/timeml-validator (if it passes try stricter validations, see help)

Just found that eid and eiid do not correspond in your file:
`<MAKEINSTANCE eiid="ei11" eventID="e13" pos="UNKNOWN" tense="NONE" />`
that should not be the problem but I would explore that too after we implement what I suggested above so we know exactly what event is causing the problem.

**Comment by hllorens** [comment]
Just found that eid and eiid do not correspond in your file:
<MAKEINSTANCE eiid="ei11" eventID="e13" pos="UNKNOWN" tense="NONE" />
 that should not be the problem but I would explore that too after we implement what I suggested above so we know exactly what event is causing the problem.

**Comment by hllorens** [comment]
@ylmeng if you need further help please let me know.

**Comment by hllorens** [comment]
@ylmeng I improved the code to break more nicely and found and fixed the exact problem.

The problem is this annotation:
`<EVENT class="OCCURRENCE" eid="e296">silence</EVENT><EVENT class="STATE" eid="e297">,</EVENT>"`

The tokenization of that becomes "silence," which can only have 1 annotation.
Now I added a rule to separate "," if it is followed by a ".

The new version of the repo should solve that and should work with your file.

The software is better thanks to you! :)

If you need further help please let me know.

**Comment by ylmeng** [comment]
@hllorens Hi hllorens thank you for digging in the problem. I have been on vacation and have not got a chance to look at it. I appreciate your work!
